tags: ['c', 'cmake', 'systemd']

steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--file=.devcontainer/Dockerfile', '--tag=localhost/cloud-builders/cmake', '.']

- name: 'localhost/cloud-builders/cmake'
  id: 'compile'
  env: ['CFLAGS=-Os']
  dir: 'build'
  entrypoint: 'bash'
  args:
  - -ce
  - |
    cmake -GNinja ..;
    ninja

# Usually you'd test the artifact.
#   I've skipped this here because GCCB won't display, on a failure, which step.
#   This way it's most likely that it didn't compile.

#artifacts:
#  objects:
#    location: 'gs://artifacts.hygienic.fun/amd64/'
#    paths: ['build/systemd-*udp*d']
