FROM blitznote/cmake:latest

ENTRYPOINT ["/bin/bash", "-c"]

RUN dpkg --list | grep -F systemd \
 && sed -i -e 's@ universe@@g' /etc/apt/sources.list \
 && apt-get -q update \
 && apt-get -y --no-install-recommends --allow-downgrades install \
      libsystemd-dev \
 && apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
