FROM marketplace.gcr.io/google/ubuntu1804

SHELL ["/bin/bash", "-c"]

RUN apt-get -q update \
 && apt-get -y --no-install-recommends --allow-downgrades install \
      gcc cmake ninja-build \
      libc6-dev \
      libsystemd-dev \
 && apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
